---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by EDY.
--- DateTime: 2023/6/13 16:18
---
STRINGS.NAMES.HANBAOBAO = "hanbaobao"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HANBAOABO = "Chinese Food"