GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})
local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.CAOMEIBEAN = "草莓"
STRINGS.NAMES.CAOMEIBEAN_COOKED = "烤熟的草莓"
STRINGS.NAMES.DUG_CAOMEIBUSH = "草莓丛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_CAOMEIBUSH = "原子重构后的草垛"
STRINGS.RECIPE_DESC.DUG_CAOMEIBUSH = "原子重构后的草莓"
STRINGS.NAMES.CAOMEIBUSH = "草莓丛"

STRINGS.NAMES.LANMEIBEAN = "蓝莓"
STRINGS.NAMES.LANMEIBEAN_COOKED = "烤熟的蓝莓"
STRINGS.NAMES.DUG_LANMEIBUSH = "蓝莓丛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_LANMEIBUSH = "原子重构后的草垛"
STRINGS.RECIPE_DESC.DUG_LANMEIBUSH = "原子重构后的蓝莓"
STRINGS.NAMES.LANMEIBUSH = "蓝莓丛"

STRINGS.NAMES.JINHUAFAZHANG = "净化法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JINHUAFAZHANG = "驱逐月灵/暗影的寄生"
STRINGS.RECIPE_DESC.JINHUAFAZHANG = "驱逐月灵/暗影的寄生····能力有限"

STRINGS.NAMES.XLG_CHANGPIAN = "星露谷·夏天的清晨"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.XLG_CHANGPIAN = "夏日的清晨"
STRINGS.RECIPE_DESC.XLG_CHANGPIAN = "夏日的清晨"

STRINGS.NAMES.CHANGPIANJI = "唱片机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHANGPIANJI = "要不试试新买的唱片？"
STRINGS.RECIPE_DESC.CHANGPIANJI = "要不试试新买的唱片？"

STRINGS.NAMES.ZHYW_CHANGPIAN = "寄生兽·最后一吻"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZHYW_CHANGPIAN = "Last Kiss"
STRINGS.RECIPE_DESC.ZHYW_CHANGPIAN = "Last kiss"

STRINGS.NAMES.XL_CHANGPIAN = "夏恋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.XL_CHANGPIAN = "风·花·雪·月"
STRINGS.RECIPE_DESC.XL_CHANGPIAN = "风·花·雪·月"

STRINGS.NAMES.CRSJBB_CHANGPIAN = "星露谷·春天的生机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRSJBB_CHANGPIAN = "春日的小曲"
STRINGS.RECIPE_DESC.CRSJBB_CHANGPIAN = "春日的小曲"

STRINGS.NAMES.SRKL_CHANGPIAN = "诞生的喜悦"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SRKL_CHANGPIAN = "生日快乐！"
STRINGS.RECIPE_DESC.SRKL_CHANGPIAN = "生日快乐！"

STRINGS.NAMES.WWHMGQB_CHANGPIAN = "未闻花名·钢琴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WWHMGQB_CHANGPIAN = "我们在玩一次躲猫猫！"
STRINGS.RECIPE_DESC.WWHMGQB_CHANGPIAN = "我们在玩一次躲猫猫！"

STRINGS.NAMES.MYJMDQT_2_CHANGPIAN = "姐姐离去的秋天2"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MYJMDQT_2_CHANGPIAN = "秋姐妹"
STRINGS.RECIPE_DESC.MYJMDQT_2_CHANGPIAN = "秋姐妹"

STRINGS.NAMES.MYJMDQT_3_CHANGPIAN = "姐姐离去的秋天3"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MYJMDQT_3_CHANGPIAN = "秋姐妹"
STRINGS.RECIPE_DESC.MYJMDQT_3_CHANGPIAN = "秋姐妹"

STRINGS.NAMES.QBY_CHANGPIAN = "千本樱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.QBY_CHANGPIAN = "千本樱"
STRINGS.RECIPE_DESC.QBY_CHANGPIAN = "千本樱"

STRINGS.NAMES.XHBKJ_CHANGPIAN = "星河不可及"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.XHBKJ_CHANGPIAN = "所念皆星河，星河不可及"
STRINGS.RECIPE_DESC.XHBKJ_CHANGPIAN = "所念皆星河，星河不可及"

STRINGS.NAMES.WWHMBYHB_CHANGPIAN = "未闻花名·八音盒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WWHMBYHB_CHANGPIAN = "我们在玩一次躲猫猫！"
STRINGS.RECIPE_DESC.WWHMBYHB_CHANGPIAN = "我们在玩一次躲猫猫！"

STRINGS.NAMES.WWHLS_CHANGPIAN = "汪汪欢乐颂"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WWHLS_CHANGPIAN = "汪星人大合唱！"
STRINGS.RECIPE_DESC.WWHLS_CHANGPIAN = "汪星人大合唱！"

STRINGS.NAMES.XRWHJ_CHANGPIAN = "夏日文化祭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.XRWHJ_CHANGPIAN = "夏日文化祭"
STRINGS.RECIPE_DESC.XRWHJ_CHANGPIAN = "夏日文化祭"

STRINGS.NAMES.FEN_CHANGPIAN = "风"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEN_CHANGPIAN = "风"
STRINGS.RECIPE_DESC.FEN_CHANGPIAN = "风"

STRINGS.NAMES.SMSNJLB_CHANGPIAN = "女巫茶会"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMSNJLB_CHANGPIAN = "女巫茶会"
STRINGS.RECIPE_DESC.SMSNJLB_CHANGPIAN = "女巫茶会"

STRINGS.NAMES.MYJMDQT_1_CHANGPIAN = "姐姐离去的秋天1"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MYJMDQT_1_CHANGPIAN = "秋姐妹"
STRINGS.RECIPE_DESC.MYJMDQT_1_CHANGPIAN = "秋姐妹"

STRINGS.NAMES.XRFL_CHANGPIAN = "夏日·风铃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.XRFL_CHANGPIAN = "夏日·风铃"
STRINGS.RECIPE_DESC.XRFL_CHANGPIAN = "夏日·风铃"

STRINGS.NAMES.JIAN = "大宝剑"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JIAN = "一起来击剑"--描述
STRINGS.RECIPE_DESC.JIAN = "击剑！" --制造描述

STRINGS.RECIPE_DESC.BUTTER = "原来你也是非酋！"

STRINGS.NAMES.PACKIM = "鹈鹕"--名称
STRINGS.NAMES.PACKIM_FISHBONE = "鱼骨"--名称

STRINGS.NAMES.JIUCAIBEAN = "韭菜"
STRINGS.NAMES.KAOJIUCAI = "烤熟的韭菜"
STRINGS.NAMES.DUG_JIUCAI = "韭菜根"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_JIUCAI = "有土栽培的韭菜"
STRINGS.RECIPE_DESC.DUG_JIUCAI = "有土栽培的韭菜"
STRINGS.NAMES.JIUCAI = "韭菜根"
STRINGS.NAMES.JIUCAIHUA = "韭菜花"

-- STRINGS.RECIPE_DESC.packim_fishbone = "击剑！" --制造描述
STRINGS.RECIPE_DESC.PACKIM_FISHBONE = "别贪心做多了也只有一只鹈鹕"

STRINGS.NAMES.BANLIBUSH = "板栗"
STRINGS.NAMES.COOKBANLI = "烤熟的板栗"
STRINGS.NAMES.DUG_BANLIBUSH = "板栗树根"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BANLIBUSH = "有土栽培的板栗"
STRINGS.RECIPE_DESC.DUG_BANLIBUSH = "有土栽培的板栗"
STRINGS.NAMES.DUG_BANLIBUSH = "板栗树苗"
STRINGS.NAMES.BANLIBEAN = "带壳的板栗"
STRINGS.NAMES.BANLIKE = "板栗外壳"
STRINGS.NAMES.BANLIBEAN1 = "板栗"



STRINGS.NAMES.SJY_MILUFAZHANG = "麋鹿法杖"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MILUFAZHANG = "一双寒冷的眼睛死死盯着你"--描述
STRINGS.RECIPE_DESC.SJY_MILUFAZHANG = "冻住不洗澡！" --制造描述

STRINGS.NAMES.SJY_ZRZN = "自然之怒"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_ZRZN= "体验一下大自然的愤怒吧"--描述
STRINGS.RECIPE_DESC.SJY_ZRZN = "感受一下五雷轰顶！！！" --制造描述

-- caomeixie
STRINGS.NAMES.SJY_WLCJ = "蔓绿翠剑"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WLCJ = "强大的再生能力"--描述
STRINGS.RECIPE_DESC.SJY_WLCJ = "再生！再生！再生！" --制造描述


STRINGS.NAMES.SJY_XIEHUANGJIANG = "蟹黄酱"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_XIEHUANGJIANG = "蟹黄酱"--描述
STRINGS.RECIPE_DESC.SJY_XIEHUANGJIANG = "蟹黄酱" --制造描述

STRINGS.NAMES.CAOMEIXIE = "草莓蟹"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAOMEIXIE = "草莓蟹"--描述
STRINGS.RECIPE_DESC.CAOMEIXIE = "草莓蟹" --制造描述

STRINGS.NAMES.SJY_LINGDIE = "灵蝶"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_LINGDIE = "灵蝶"--描述
STRINGS.RECIPE_DESC.SJY_LINGDIE = "灵蝶" --制造描述

STRINGS.NAMES.SJY_WSJ_MEIQIUGUAI2 = "霉球怪"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_MEIQIUGUAI2 = "发霉的东西成精啦？"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_MEIQIUGUAI2 = "好像是活的" --制造描述

STRINGS.NAMES.SJY_BIANFUZHUTAI = "蝙蝠烛台"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BIANFUZHUTAI = "这对蝙蝠翅膀让我感到不详！"--描述
STRINGS.RECIPE_DESC.SJY_BIANFUZHUTAI = "还好他不能动" --制造描述

STRINGS.NAMES.SJY_DAODANGUI = "捣蛋鬼"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DAODANGUI = "他不会突然动起来吧？"--描述
STRINGS.RECIPE_DESC.SJY_DAODANGUI = "我还是不要靠近他好！" --制造描述

STRINGS.NAMES.SJY_HUANGSENANGUADENG = "黄色南瓜灯"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGSENANGUADENG = "可惜不能吃了"--描述
STRINGS.RECIPE_DESC.SJY_HUANGSENANGUADENG = "夜晚来点不一样的？" --制造描述

STRINGS.NAMES.SJY_WSJ_LAZHUNANGUA = "南瓜烛台"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_LAZHUNANGUA = "一堆凉飕飕的蜡烛"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_LAZHUNANGUA = "希望他不会有安全隐患" --制造描述

STRINGS.NAMES.SJY_WSJ_LVSENANGUADENG = "绿色南瓜灯"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_LVSENANGUADENG = "他的光不一样"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_LVSENANGUADENG = "有东西被困住在里面" --制造描述

STRINGS.NAMES.SJY_WSJ_MEIQIUGUAI = "霉球怪"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_MEIQIUGUAI = "他们是一个团体吗？"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_MEIQIUGUAI = "活的！" --制造描述

STRINGS.NAMES.SJY_WSJ_MEIQIUTUANZI = "霉球怪"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_MEIQIUTUANZI = "不止一个！"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_MEIQIUTUANZI = "会动！" --制造描述

STRINGS.NAMES.SJY_WSJ_NANGUALAZHU = "南瓜蜡烛"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_NANGUALAZHU = "一堆蜡烛"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_NANGUALAZHU = "小心火灾" --制造描述

STRINGS.NAMES.SJY_WSJ_PUTONGZHUTAI = "普通烛台"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_PUTONGZHUTAI = "平平无奇的烛台"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_PUTONGZHUTAI = "好怀念呀！" --制造描述

STRINGS.NAMES.SJY_WSJ_YOULING = "幽灵装饰"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_YOULING = "虽然是假的但还是有点害怕"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_YOULING = "会不会活过来呀？" --制造描述

STRINGS.NAMES.SJY_WSJ_YOULINGS = "幽灵摆设"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_YOULINGS = "可爱中透露着诡异"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_YOULINGS = "还是放远点观赏好了" --制造描述

STRINGS.NAMES.SJY_YOUYUXU = "鱿鱼须"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_YOUYUXU = "动来动去好恶心"--描述

STRINGS.NAMES.SJY_YOUYUXU_COOKED = "烤熟的鱿鱼须"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_YOUYUXU_COOKED = "香喷喷的海鲜"--描述


STRINGS.NAMES.SJY_XIAOMAI = "小麦"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_XIAOMAI = "小麦"--描述
STRINGS.RECIPE_DESC.SJY_XIAOMAI = "又是大丰收" --制造描述

STRINGS.NAMES.SJY_XIAOMAIBEAN = "小麦穗"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_XIAOMAIBEAN = "小麦穗"--描述
STRINGS.RECIPE_DESC.SJY_XIAOMAIBEAN = "颗粒饱满！" --制造描述

STRINGS.NAMES.SJY_MIANFEN = "面粉"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MIANFEN = "小麦研磨加工而成"--描述
STRINGS.RECIPE_DESC.SJY_MIANFEN = "优质面粉！" --制造描述

STRINGS.NAMES.DUG_SJY_XIAOMAI = "小麦根"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_XIAOMAI = "原子重构后的小麦"--描述
STRINGS.RECIPE_DESC.DUG_SJY_XIAOMAI = "这是原子重构吗？" --制造描述


STRINGS.NAMES.SJY_HUANGGUABUSH = "黄瓜植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGGUABUSH = "普普通通的黄瓜"--描述
STRINGS.RECIPE_DESC.SJY_HUANGGUABUSH = "这是什么新奇植物？" --制造描述


STRINGS.NAMES.SJY_HUANGGUABEAN = "黄瓜"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGGUABEAN = "兄弟你好细"--描述
STRINGS.RECIPE_DESC.SJY_HUANGGUABEAN = "黄瓜" --制造描述

STRINGS.NAMES.SJY_HUANGGUABEAN_COOKED = "烤熟的黄瓜"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGGUABEAN_COOKED = "或许不能外敷了"--描述
STRINGS.RECIPE_DESC.SJY_HUANGGUABEAN_COOKED = "熟黄瓜" --制造描述

STRINGS.NAMES.DUG_SJY_HUANGGUABUSH = "黄瓜幼苗"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_HUANGGUABUSH = "或许我该种下去"--描述
STRINGS.RECIPE_DESC.DUG_SJY_HUANGGUABUSH = "这是什么变异" --制造描述

STRINGS.NAMES.SJY_ZHUOZI_TABLE = "木质大餐桌"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_ZHUOZI_TABLE = "或许我可以请朋友吃我亲手做的饭"--描述
STRINGS.RECIPE_DESC.SJY_ZHUOZI_TABLE = "我不敢想象他该有多大" --制造描述

STRINGS.NAMES.SJY_BIWANGWO = "必忘我植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BIWANGWO = "这样就可以随时注意到你啦"--描述
STRINGS.RECIPE_DESC.SJY_BIWANGWO = "小家伙快长大！" --制造描述

STRINGS.NAMES.DUG_SJY_BIWANGWO = "必忘我种子"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_BIWANGWO = "小小的花卉种子"--描述
STRINGS.RECIPE_DESC.DUG_SJY_BIWANGWO = "小家伙快快长大！" --制造描述

STRINGS.NAMES.SJY_HUANGJIAMENGWEI = "皇家萌卫"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGJIAMENGWEI = "工作的小曲"--描述
STRINGS.RECIPE_DESC.SJY_HUANGJIAMENGWEI = "皇家萌卫" --制造描述

STRINGS.NAMES.SJY_GUANGZHU = "无尽棱镜"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_GUANGZHU = "他容纳了无尽的光芒"--描述
STRINGS.RECIPE_DESC.SJY_GUANGZHU = "比太阳还耀眼" --制造描述

STRINGS.NAMES.SJY_DADOUBUSH = "奇异豆植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DADOUBUSH = "好奇怪的豆子"--描述
STRINGS.RECIPE_DESC.SJY_DADOUBUSH = "独特的豆子" --制造描述

STRINGS.NAMES.DUG_SJY_DADOUBUSH = "干枯的奇异豆植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_DADOUBUSH = "或许还有存活的可能"--描述
STRINGS.RECIPE_DESC.DUG_SJY_DADOUBUSH = "奇怪的豆子！" --制造描述

STRINGS.NAMES.SJY_DONGGUABUSH = "矮冬瓜植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DONGGUABUSH = "好像是这里独特的品种"--描述
STRINGS.RECIPE_DESC.SJY_DONGGUABUSH = "很独特" --制造描述

STRINGS.NAMES.DUG_SJY_DONGGUABUSH = "矮冬瓜幼苗"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_DONGGUABUSH = "这能存活吗？"--描述
STRINGS.RECIPE_DESC.DUG_SJY_DONGGUABUSH = "希望他能存活" --制造描述

STRINGS.NAMES.SJY_DADOUBEAN = "奇异毛豆"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DADOUBEAN = "跟他名字一样"--描述
STRINGS.RECIPE_DESC.SJY_DADOUBEAN = "奇怪的豆子！" --制造描述

STRINGS.NAMES.SJY_DONGGUABEAN = "矮冬瓜"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DONGGUABEAN = "希望他会好吃"--描述
STRINGS.RECIPE_DESC.SJY_DONGGUABEAN = "矮冬瓜" --制造描述

STRINGS.NAMES.SJY_DONGGUAPIAN = "矮冬瓜片"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DONGGUAPIAN = "或许可以用来外敷？"--描述
STRINGS.RECIPE_DESC.SJY_DONGGUAPIAN = "一个冬瓜居然可以产那么多！" --制造描述

STRINGS.NAMES.SJY_LVDOUBEAN = "奇异绿豆"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_LVDOUBEAN = "会不会有我的口水"--描述
STRINGS.RECIPE_DESC.SJY_LVDOUBEAN = "奇怪的绿豆子" --制造描述

STRINGS.NAMES.SJY_HUANGDOUBEAN = "奇异黄豆"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGDOUBEAN = "是绿豆干了吗？"--描述
STRINGS.RECIPE_DESC.SJY_HUANGDOUBEAN = "奇怪的黄豆子" --制造描述

STRINGS.NAMES.SJY_HONGDOUBEAN = "奇异红豆"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HONGDOUBEAN = "是王维诗里的红豆！"--描述
STRINGS.RECIPE_DESC.SJY_HONGDOUBEAN = "奇怪的红豆子" --制造描述

STRINGS.NAMES.SJY_HEIDOUBEAN = "奇异黑豆"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HEIDOUBEAN = "红豆发黑了？"--描述
STRINGS.RECIPE_DESC.SJY_HEIDOUBEAN = "奇怪的黑豆子" --制造描述

STRINGS.NAMES.SJY_WSJ_LIMAO = "万圣节捣蛋鬼帽子"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WSJ_LIMAO = "这个帽子不怀好意"--描述
STRINGS.RECIPE_DESC.SJY_WSJ_LIMAO = "千万别把他放地上！" --制造描述

STRINGS.NAMES.SJY_MOGU_TABLE = "大力菇餐桌"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MOGU_TABLE = "大力菇餐桌"--描述
STRINGS.RECIPE_DESC.SJY_MOGU_TABLE = "大力菇餐桌" --制造描述

STRINGS.NAMES.SJY_MOGU2_TABLE = "平头菇餐桌"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MOGU2_TABLE = "平头菇餐桌"--描述
STRINGS.RECIPE_DESC.SJY_MOGU2_TABLE = "平头菇餐桌" --制造描述

STRINGS.NAMES.SJY_MOGU3_TABLE = "莲叶餐桌"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MOGU3_TABLE = "莲叶餐桌"--描述
STRINGS.RECIPE_DESC.SJY_MOGU3_TABLE = "莲叶餐桌" --制造描述

STRINGS.NAMES.SJY_MOGU4_TABLE = "莲叶餐桌"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MOGU4_TABLE = "莲叶餐桌"--描述
STRINGS.RECIPE_DESC.SJY_MOGU4_TABLE = "莲叶餐桌" --制造描述

STRINGS.NAMES.SJY_JIANGBINGXIANG1 = "积雪姜饼箱子"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_JIANGBINGXIANG1 = "积雪姜饼箱子"--描述
STRINGS.RECIPE_DESC.SJY_JIANGBINGXIANG1 = "积雪姜饼箱子" --制造描述

STRINGS.NAMES.SJY_WANSHENGJIEGUO = "万圣节烹饪锅"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_WANSHENGJIEGUO = "万圣节料理专属烹饪锅"--描述
STRINGS.RECIPE_DESC.SJY_WANSHENGJIEGUO = "只能烹饪出万圣节料理" --制造描述

STRINGS.NAMES.SJY_HEILUSHUI = "黑卤水"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HEILUSHUI = "黑卤水"--描述
STRINGS.RECIPE_DESC.SJY_HEILUSHUI = "黑卤水" --制造描述

STRINGS.NAMES.SJY_CHOUDOUFU = "臭豆腐"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_CHOUDOUFU = "臭豆腐"--描述
STRINGS.RECIPE_DESC.SJY_CHOUDOUFU = "臭豆腐" --制造描述

STRINGS.NAMES.SJY_SHOUCHONGYANGNAI = "手冲羊奶"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_SHOUCHONGYANGNAI = "手冲羊奶"--描述
STRINGS.RECIPE_DESC.SJY_SHOUCHONGYANGNAI = "手冲羊奶" --制造描述

STRINGS.NAMES.SJY_SHIGAOFEN = "石膏粉"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_SHIGAOFEN = "石膏粉"--描述
STRINGS.RECIPE_DESC.SJY_SHIGAOFEN = "石膏粉" --制造描述

STRINGS.NAMES.SJY_JIANGBINGXIANG2 = "积雪姜饼箱子2"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_JIANGBINGXIANG2 = "积雪姜饼箱子2"--描述
STRINGS.RECIPE_DESC.SJY_JIANGBINGXIANG2 = "积雪姜饼箱子2" --制造描述

STRINGS.NAMES.SJY_JIANGBINGXIANG3 = "积雪姜饼箱子3"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_JIANGBINGXIANG3 = "积雪姜饼箱子3"--描述
STRINGS.RECIPE_DESC.SJY_JIANGBINGXIANG3 = "积雪姜饼箱子3" --制造描述

STRINGS.NAMES.SJY_GUDONGBI = "咕咚币"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_GUDONGBI = "咕咚国王发行的货币！"--描述
STRINGS.RECIPE_DESC.SJY_GUDONGBI = "咕咚超市货币" --制造描述

STRINGS.NAMES.SJY_KEKOUKELE = "Coca-Cola"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_KEKOUKELE = "是可口可乐！！！"--描述
STRINGS.RECIPE_DESC.SJY_KEKOUKELE = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_CHENGZHIWEIFENDA = "橙子味芬达"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_CHENGZHIWEIFENDA = "这是橙子味芬达"--描述
STRINGS.RECIPE_DESC.SJY_CHENGZHIWEIFENDA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_CAOMEIWEIMEINIANDA = "草莓味美年达"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_CAOMEIWEIMEINIANDA = "这是草莓味美年达"--描述
STRINGS.RECIPE_DESC.SJY_CAOMEIWEIMEINIANDA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_XUEBI = "雪碧"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_XUEBI = "这是雪碧"--描述
STRINGS.RECIPE_DESC.SJY_XUEBI = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_BOLUOPI = "菠萝啤"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOLUOPI = "这是菠萝啤"--描述
STRINGS.RECIPE_DESC.SJY_BOLUOPI = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_YUANWEISHUPIAN = "原味薯片"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_YUANWEISHUPIAN = "这是原味薯片"--描述
STRINGS.RECIPE_DESC.SJY_YUANWEISHUPIAN = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_HUANGGUAWEISHUPIAN = "黄瓜味薯片"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HUANGGUAWEISHUPIAN = "这是黄瓜味薯片"--描述
STRINGS.RECIPE_DESC.SJY_HUANGGUAWEISHUPIAN = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_FANQIEWEISHUPIAN = "番茄味薯片"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_FANQIEWEISHUPIAN = "这是番茄味薯片"--描述
STRINGS.RECIPE_DESC.SJY_FANQIEWEISHUPIAN = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_NINGMENGWEISHUPIAN = "柠檬味薯片"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_NINGMENGWEISHUPIAN = "这是柠檬味薯片"--描述
STRINGS.RECIPE_DESC.SJY_NINGMENGWEISHUPIAN = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_MOLIHUACHA = "茉莉花茶"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_MOLIHUACHA = "这是茉莉花茶"--描述
STRINGS.RECIPE_DESC.SJY_MOLIHUACHA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_LVCHA = "绿茶"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_LVCHA = "这是绿茶"--描述
STRINGS.RECIPE_DESC.SJY_LVCHA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_COCOKELE = "口渴可乐"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_COCOKELE = "这是口渴可乐"--描述
STRINGS.RECIPE_DESC.SJY_COCOKELE = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_XBI = "雷碧"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_XBI = "这是雷碧"--描述
STRINGS.RECIPE_DESC.SJY_XBI = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_CHENGZHIWEIMEINIANDA = "橙子味美年达"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_CHENGZHIWEIMEINIANDA = "这是橙子味美年达"--描述
STRINGS.RECIPE_DESC.SJY_CHENGZHIWEIMEINIANDA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_PUTAOWEIMEINIANDA = "葡萄味美年达"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_PUTAOWEIMEINIANDA = "这是葡萄味美年达"--描述
STRINGS.RECIPE_DESC.SJY_PUTAOWEIMEINIANDA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_PINGGUOWEIMEINIANDA = "苹果味美年达"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_PINGGUOWEIMEINIANDA = "这是苹果味美年达"--描述
STRINGS.RECIPE_DESC.SJY_PINGGUOWEIMEINIANDA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_PUTONGPIJIU = "普通啤酒"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_PUTONGPIJIU = "这是普通啤酒"--描述
STRINGS.RECIPE_DESC.SJY_PUTONGPIJIU = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_YANJINPIJIU = "燕京啤酒"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_YANJINPIJIU = "这是燕京啤酒"--描述
STRINGS.RECIPE_DESC.SJY_YANJINPIJIU = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_HONGJIU = "红酒"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_HONGJIU = "这是红酒"--描述
STRINGS.RECIPE_DESC.SJY_HONGJIU = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_LINZHUS = "星灰"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_LINZHUS = "店长说还是远离日光好"--描述
STRINGS.RECIPE_DESC.SJY_LINZHUS = "咕咚超市特卖-小心点他可见不得日光" --制造描述


STRINGS.NAMES.SJY_BOLUOBUSH = "菠萝植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOLUOBUSH = "菠萝植株"--描述
STRINGS.RECIPE_DESC.SJY_BOLUOBUSH = "菠萝植株" --制造描述

STRINGS.NAMES.SJY_BOLUOBEAN = "菠萝"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOLUOBEAN = "菠萝"--描述
STRINGS.RECIPE_DESC.SJY_BOLUOBEAN = "菠萝" --制造描述

STRINGS.NAMES.DUG_SJY_BOLUOBUSH = "菠萝根茎"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_BOLUOBUSH = "菠萝根茎"--描述
STRINGS.RECIPE_DESC.DUG_SJY_BOLUOBUSH = "菠萝根茎" --制造描述

STRINGS.NAMES.DUG_SJY_SHUIDAOBUSH = "旱稻幼苗"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_SJY_SHUIDAOBUSH = "旱稻幼苗"--描述
STRINGS.RECIPE_DESC.DUG_SJY_SHUIDAOBUSH = "旱稻幼苗" --制造描述

STRINGS.NAMES.SJY_SHUIDAOBUSH = "旱稻植株"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_SHUIDAOBUSH = "旱稻植株"--描述
STRINGS.RECIPE_DESC.SJY_SHUIDAOBUSH = "旱稻植株" --制造描述

STRINGS.NAMES.SJY_GUZI = "谷子"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_GUZI = "谷子"--描述
STRINGS.RECIPE_DESC.SJY_GUZI = "谷子" --制造描述

STRINGS.NAMES.SJY_DAMI = "大米"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_DAMI = "大米"--描述
STRINGS.RECIPE_DESC.SJY_DAMI = "加工成大米" --制造描述

STRINGS.NAMES.SJY_NINGMENGWEIFENDA = "柠檬味芬达"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_NINGMENGWEIFENDA = "这是柠檬味芬达"--描述
STRINGS.RECIPE_DESC.SJY_NINGMENGWEIFENDA = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_JIANGYOU = "酱油"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_JIANGYOU = "这是做饭用的酱油"--描述
STRINGS.RECIPE_DESC.SJY_JIANGYOU = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_ZHIWUSHIYONGYOU = "植物食用油"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_ZHIWUSHIYONGYOU = "这是做饭用的植物油"--描述
STRINGS.RECIPE_DESC.SJY_ZHIWUSHIYONGYOU = "咕咚超市特卖" --制造描述

STRINGS.NAMES.SJY_CHITANG = "龙虾池塘"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_CHITANG = "龙虾池塘"--描述
STRINGS.RECIPE_DESC.SJY_CHITANG = "龙虾池塘" --制造描述


STRINGS.NAMES.SJY_SHUIQIUJI = "水球机"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_SHUIQIUJI = "水球机"--描述
STRINGS.RECIPE_DESC.SJY_SHUIQIUJI = "水球机" --制造描述

STRINGS.NAMES.SJY_BOOK_IKEA_GUIDEBOOK = "宜家指南"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOOK_IKEA_GUIDEBOOK = "超实用的搬家指南"--描述
STRINGS.RECIPE_DESC.SJY_BOOK_IKEA_GUIDEBOOK = "或许我可以按照书上的内容选择搬家方式" --制造描述


STRINGS.NAMES.SJY_BOOK_GEMSTONE = "矿石宝典"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOOK_GEMSTONE = "这里面记录很多已知的矿石"--描述
STRINGS.RECIPE_DESC.SJY_BOOK_GEMSTONE = "要是可以凭空出现就好了" --制造描述

STRINGS.NAMES.SJY_BOOK_DEVOUR = "真·暗影秘典"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOOK_DEVOUR = "他似乎比麦斯威尔手里的那本更厉害"--描述
STRINGS.RECIPE_DESC.SJY_BOOK_DEVOUR = "我好像要被他吞噬了" --制造描述

STRINGS.NAMES.SJY_BOOK_BIRDS = "新·世界鸟类大全"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_BOOK_BIRDS = "这里记录的鸟儿更加全面"--描述
STRINGS.RECIPE_DESC.SJY_BOOK_BIRDS = "好多鸟儿！" --制造描述

STRINGS.NAMES.SJY_ZHUDACHANG = "猪大肠"--名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SJY_ZHUDACHANG = "好恶心！"--描述
STRINGS.RECIPE_DESC.SJY_ZHUDACHANG = "好恶心！" --制造描述


