---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by EDY.
--- DateTime: 2023/6/14 18:23
---

-- 加载贴图，动画
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LWSSHR = "这魔鬼般的辣味是怎么回事?"

local assets = {Asset("ANIM", "anim/lwsshr.zip"), Asset("IMAGE", "images/lwsshr.tex"), Asset("ATLAS", "images/lwsshr.xml")}

local function oneaten(inst, eater)
    if eater.components.timer and eater:HasTag("player") then -- 判断是玩家
        if eater.components.combat ~= nil then --这个buff需要攻击组件
            eater.time_l_strengthenhancer = { replace_min = TUNING.SEG_TIME*64 }
            eater.components.debuffable:AddDebuff("buff_attack", "buff_attack")
        eater.components.talker:Say("切成星形的胡萝卜为菜品增添了不少可爱度…不好")		
            end
        end
end

function fn()
    local assetname = "lwsshr"

    local inst = CreateEntity() -- 创建实体
    inst.entity:AddTransform() -- 添加xyz形变对象
    inst.entity:AddAnimState() -- 添加动画状态
    inst.entity:AddNetwork() -- 添加这一行才能让所有客户端都能看到这个实体

    MakeInventoryPhysics(inst)

    inst.AnimState:SetBank(assetname) -- 地上动画
    inst.AnimState:SetBuild(assetname) -- 材质包，就是anim里的zip包
    inst.AnimState:PlayAnimation("idle") -- 默认播放哪个动画
    inst:AddTag("preparedfood")  --可由烹饪得到的食物否则大厨无法食用
    MakeInventoryFloatable(inst)
    --------------------------------------------------------------------------
    if not TheWorld.ismastersim then
        return inst
    end
    --------------------------------------------------------------------------
    inst:AddComponent("inspectable") -- 可检查组件
    inst:AddComponent("inventoryitem") -- 物品组件

    inst.components.inventoryitem.atlasname = "images/lwsshr.xml" -- 在背包里的贴图

    inst:AddComponent("edible") -- 可食物组件
    inst.components.edible.foodtype = FOODTYPE.GOODIES

    inst:AddComponent("perishable") -- 可腐烂的组件
    inst.components.perishable:SetPerishTime(TUNING.PERISH_SUPERSLOW)
    inst.components.perishable:StartPerishing()
    inst.components.perishable.onperishreplacement = "spoiled_food" -- 腐烂后变成腐烂食物

    inst.components.edible.healthvalue = 20
    inst.components.edible.hungervalue = 75
    inst.components.edible.sanityvalue = 15
    inst.components.edible:SetOnEatenFn(oneaten)--吃的时候调用buff效果
    inst:AddComponent("stackable") -- 可堆叠
    inst.components.stackable.maxsize = TUNING.STACK_SIZE_SMALLITEM


    MakeHauntableLaunch(inst)

    return inst
end

return Prefab("lwsshr", fn, assets, prefabs)