---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by EDY.
--- DateTime: 2023/6/14 18:23
---

-- 加载贴图，动画
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NXJGCT = "口感酥脆的小吃"

local assets = {Asset("ANIM", "anim/nxjgct.zip"), Asset("IMAGE", "images/nxjgct.tex"), Asset("ATLAS", "images/nxjgct.xml")}

local function oneaten(inst, eater)
    if eater.components.timer and eater:HasTag("player") then -- 判断是玩家
        if eater.components.combat ~= nil then --这个buff需要攻击组件
            eater.time_l_strengthenhancer = { replace_min = TUNING.SEG_TIME*320 }
            eater.components.debuffable:AddDebuff("buff_workeffectiveness", "buff_workeffectiveness")
        eater.components.talker:Say("若有似无的奶香在舌尖微微化开，柔韧的菌菇与其融合，随着松脆面包片的咔嚓咔嚓声…这无与伦比的满足感，让人连指尖残留的面包屑都不想要放过!!!")		
            end
        end
end

function fn()
    local assetname = "nxjgct"

    local inst = CreateEntity() -- 创建实体
    inst.entity:AddTransform() -- 添加xyz形变对象
    inst.entity:AddAnimState() -- 添加动画状态
    inst.entity:AddNetwork() -- 添加这一行才能让所有客户端都能看到这个实体

    MakeInventoryPhysics(inst)

    inst.AnimState:SetBank(assetname) -- 地上动画
    inst.AnimState:SetBuild(assetname) -- 材质包，就是anim里的zip包
    inst.AnimState:PlayAnimation("idle") -- 默认播放哪个动画
    inst:AddTag("preparedfood")  --可由烹饪得到的食物否则大厨无法食用
    MakeInventoryFloatable(inst)
    --------------------------------------------------------------------------
    if not TheWorld.ismastersim then
        return inst
    end
    --------------------------------------------------------------------------
    inst:AddComponent("inspectable") -- 可检查组件
    inst:AddComponent("inventoryitem") -- 物品组件

    inst.components.inventoryitem.atlasname = "images/nxjgct.xml" -- 在背包里的贴图

    inst:AddComponent("edible") -- 可食物组件
    inst.components.edible.foodtype = FOODTYPE.GOODIES

    inst:AddComponent("perishable") -- 可腐烂的组件
    inst.components.perishable:SetPerishTime(TUNING.PERISH_SUPERSLOW)
    inst.components.perishable:StartPerishing()
    inst.components.perishable.onperishreplacement = "spoiled_food" -- 腐烂后变成腐烂食物

    inst.components.edible.healthvalue = 40
    inst.components.edible.hungervalue = 66.5
    inst.components.edible.sanityvalue = -33
    inst.components.edible:SetOnEatenFn(oneaten)--吃的时候调用buff效果
    inst:AddComponent("stackable") -- 可堆叠
    inst.components.stackable.maxsize = TUNING.STACK_SIZE_SMALLITEM


    MakeHauntableLaunch(inst)

    return inst
end

return Prefab("nxjgct", fn, assets, prefabs)