---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by EDY.
--- DateTime: 2023/6/14 18:23
---

-- 加载贴图，动画
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TSDKZ = "清新时尚的无酒精饮品。"

local assets = {Asset("ANIM", "anim/sjy_lajiaobingjiling.zip"), Asset("IMAGE", "images/sjy_lajiaobingjiling.tex"), Asset("ATLAS", "images/sjy_lajiaobingjiling.xml")}

local function oneaten(inst, eater)
    if eater.components.timer and eater:HasTag("player") then -- 判断是玩家
        if eater.components.combat ~= nil then --这个buff需要攻击组件
            eater.time_l_strengthenhancer = { replace_min = TUNING.SEG_TIME*320 }
            eater.components.debuffable:AddDebuff("buff_attack", "buff_attack")
            -- eater.components.talker:Say("十分提神的必忘我饮料，用发光浆果加以装饰，散发着雅致的清香!!!")		
            end
        if eater and eater.components.temperature then
            eater.components.temperature:SetTemperature(eater.components.temperature.current - 20)
            eater.components.talker:Say("真凉快")
        end
     end
       
end

function fn()
    local assetname = "sjy_lajiaobingjiling"

    local inst = CreateEntity() -- 创建实体
    inst.entity:AddTransform() -- 添加xyz形变对象
    inst.entity:AddAnimState() -- 添加动画状态
    inst.entity:AddNetwork() -- 添加这一行才能让所有客户端都能看到这个实体

    MakeInventoryPhysics(inst)

    inst.AnimState:SetBank(assetname) -- 地上动画
    inst.AnimState:SetBuild(assetname) -- 材质包，就是anim里的zip包
    inst.AnimState:PlayAnimation("idle") -- 默认播放哪个动画
    inst:AddTag("preparedfood")  --可由烹饪得到的食物否则大厨无法食用
    inst:AddTag("sjy_ice_cream_veggie")

    MakeInventoryFloatable(inst)
    --------------------------------------------------------------------------
    if not TheWorld.ismastersim then
        return inst
    end
    --------------------------------------------------------------------------
    inst:AddComponent("inspectable") -- 可检查组件
    inst:AddComponent("inventoryitem") -- 物品组件



    inst.components.inventoryitem.atlasname = "images/sjy_lajiaobingjiling.xml" -- 在背包里的贴图

    inst:AddComponent("edible") -- 可食物组件
    inst.components.edible.foodtype = FOODTYPE.GOODIES

    inst:AddComponent("perishable") -- 可腐烂的组件
    inst.components.perishable:SetPerishTime(TUNING.PERISH_SUPERSLOW)
    inst.components.perishable:StartPerishing()
    inst.components.perishable.onperishreplacement = "spoiled_food" -- 腐烂后变成腐烂食物

    inst.components.edible.healthvalue = -25
    inst.components.edible.hungervalue = 15
    inst.components.edible.sanityvalue = 150
    inst.components.edible:SetOnEatenFn(oneaten)--吃的时候调用buff效果
    inst:AddComponent("stackable") -- 可堆叠
    inst.components.stackable.maxsize = TUNING.STACK_SIZE_SMALLITEM


    MakeHauntableLaunch(inst)

    return inst
end

return Prefab("sjy_lajiaobingjiling", fn, assets, prefabs)