---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by EDY.
--- DateTime: 2023/6/14 18:23
---

-- 加载贴图，动画
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TSDKZ = "清新时尚的无酒精饮品。"

local assets = {Asset("ANIM", "anim/sjy_boluopi.zip"),Asset("IMAGE", "images/inventoryimages/sjy_boluopi.tex"),Asset("ATLAS", "images/inventoryimages/sjy_boluopi.xml")}

local function oneaten(inst, eater)
    if eater.components.timer and eater:HasTag("player") then -- 判断是玩家
        if eater.components.combat ~= nil then --这个buff需要攻击组件
            -- eater.time_l_strengthenhancer = { replace_min = TUNING.SEG_TIME }
            eater.components.debuffable:AddDebuff("sjy_buff_waterball", "sjy_buff_waterball")
            eater.components.talker:Say("菠萝啤！！！")		
            end

        -- if eater.components.freezable then
        --      eater.components.freezable:AddColdness(10)
        --      eater.components.talker:Say("草莓蓝莓混杂在一起让冰块更加清爽!!!")	
        --  end


    -- elseif eater.components.timer and eater:HasTag("player") or not eater.prefab =="waxwell"  then
    --     if eater.components.combat ~= nil then --这个buff需要攻击组件
    --         -- eater.time_l_strengthenhancer = { replace_min = TUNING.SEG_TIME }
    --         eater.components.debuffable:AddDebuff("sweettea_buff", "sweettea_buff")
    --         eater.components.talker:Say("夜晚的气息!!!!")		
    --         end
    
    end
    
end

function fn()
    local assetname = "sjy_boluopi"

    local inst = CreateEntity() -- 创建实体
    inst.entity:AddTransform() -- 添加xyz形变对象
    inst.entity:AddAnimState() -- 添加动画状态
    inst.entity:AddNetwork() -- 添加这一行才能让所有客户端都能看到这个实体

    MakeInventoryPhysics(inst)

    inst.AnimState:SetBank(assetname) -- 地上动画
    inst.AnimState:SetBuild(assetname) -- 材质包，就是anim里的zip包
    inst.AnimState:PlayAnimation("idle") -- 默认播放哪个动画
    inst:AddTag("preparedfood")  --可由烹饪得到的食物否则大厨无法食用
    -- inst:AddTag("sjy_ice_cream_fruit")

    MakeInventoryFloatable(inst)
    --------------------------------------------------------------------------
    if not TheWorld.ismastersim then
        return inst
    end
    --------------------------------------------------------------------------
    inst:AddComponent("inspectable") -- 可检查组件
    inst:AddComponent("inventoryitem") -- 物品组件



    inst.components.inventoryitem.atlasname = "images/inventoryimages/sjy_boluopi.xml" -- 在背包里的贴图

    inst:AddComponent("edible") -- 可食物组件
    inst.components.edible.foodtype = FOODTYPE.GOODIES

    inst.components.edible.healthvalue = -1
    inst.components.edible.hungervalue = 4.6
    inst.components.edible.sanityvalue = 50
    inst.components.edible:SetOnEatenFn(oneaten)--吃的时候调用buff效果
    inst:AddComponent("stackable") -- 可堆叠
    inst.components.stackable.maxsize = TUNING.STACK_SIZE_SMALLITEM


    MakeHauntableLaunch(inst)

    return inst
end

return Prefab("sjy_boluopi", fn, assets, prefabs)